/**
 * Library System API
 * REST API для керування книгами та авторами у бібліотечній системі
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Author {
    'id'?: number;
    'name'?: string;
    'bio'?: string;
    'birthDate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "bio",
            "baseName": "bio",
            "type": "string"
        },
        {
            "name": "birthDate",
            "baseName": "birth_date",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Author.attributeTypeMap;
    }
}

