/**
 * Library System API
 * REST API для керування книгами та авторами у бібліотечній системі
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Book {
    'id'?: number;
    'title'?: string;
    'isbn'?: string;
    'publishedDate'?: string;
    'authorId'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "isbn",
            "baseName": "isbn",
            "type": "string"
        },
        {
            "name": "publishedDate",
            "baseName": "published_date",
            "type": "string"
        },
        {
            "name": "authorId",
            "baseName": "author_id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Book.attributeTypeMap;
    }
}

